name: PHP Codeception Tests - min version

on:
  push:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub/module-coding-standards/.github/workflows/codeception-min-version.yml@main
    with:
      module-id: example-basic
      use-rest-module: false